version: '3'

networks:
  app-net:
   driver: bridge
services:
  redis:
    image: redis
    ports:
     - "6380:6379"
    volumes:
     - ./cache/redis/redis.conf:/usr/local/etc/redis/redis.conf
     - ./cache/redis:/usr/local/etc/redis
    
    networks:
     - app-net
  web:
   image: nginx:stable-alpine3.17
   container_name: web
   restart: unless-stopped
   tty: true
   ports:
   - "8088:80"
   volumes: 
    - ./src:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   depends_on:
   - app
   - mysql
   tty: true
   networks:
    - app-net
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
     - "4306:3306"
    volumes:
     - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
    - app-net
  app:
    build:
     context: ./docker/app
     dockerfile:  Dockerfile
    container_name: app
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:80"
    networks:
    - app-net
